In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
# Introduction to tensors

In [6]:
# scalar tensors
scalar=torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

Vector



In [9]:
vector=torch.tensor([7,7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
matrix=torch.tensor([
    [1,8,8],
    [9,10,100]
])

In [13]:
matrix.shape


torch.Size([2, 3])

Random tensors

In [14]:
RAND=torch.rand(2,3,4)
print(RAND)

tensor([[[0.9082, 0.5442, 0.0377, 0.4582],
         [0.8991, 0.1502, 0.0322, 0.0438],
         [0.6750, 0.4015, 0.2882, 0.3008]],

        [[0.4865, 0.3353, 0.4512, 0.8661],
         [0.9069, 0.0962, 0.3262, 0.6711],
         [0.9882, 0.0010, 0.9029, 0.3024]]])


In [15]:
RAND.shape

torch.Size([2, 3, 4])

zeros

In [16]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

ones

In [17]:
ONES=torch.ones(3,4)
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ONES.dtype

torch.float32

Creating a range of tensors

In [19]:
torch.arange(0,100)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

creating tensors like

In [20]:
ZEROS=torch.zeros_like(input=ONES)
ZEROS

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Datatypes

In [21]:
ND=torch.zeros(100,100,dtype=torch.int32)
ND

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.int32)

In [22]:
FIRST=torch.tensor([[1,2,3],[4,5,6]])
SECOND=torch.tensor([[10,20],[40,50],[30,60]])

In [23]:
# matrix multiplication / DOT PRODUCT
torch.matmul(FIRST,SECOND)

tensor([[180, 300],
        [420, 690]])

In [24]:
# Transpose-->T
FIRST.T
FIRST.T*SECOND #-->Simple multiply

tensor([[ 10,  80],
        [ 80, 250],
        [ 90, 360]])

Aggregate Functions

In [25]:
X=torch.rand(10)
X

tensor([0.1470, 0.5430, 0.8224, 0.7639, 0.3431, 0.5605, 0.8408, 0.1449, 0.2282,
        0.3959])

In [26]:
torch.min(X)
torch.max(X)
X.max()
X.mean()
X.sum()
print(f"the minimum value is at position {X.argmin()}")

the minimum value is at position 7


Reshaping, stacking, squeezing and unsqueezing

In [27]:
x=torch.arange(1,10)

x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [28]:
x_reshaped=x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
# View shares memory with initial variable whereas reshape doesnot

z=x.view(1,9)
z[0][0]=100
z,x


(tensor([[100,   2,   3,   4,   5,   6,   7,   8,   9]]),
 tensor([100,   2,   3,   4,   5,   6,   7,   8,   9]))

In [30]:
# Stacking tensors on top of eachother
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[100,   2,   3,   4,   5,   6,   7,   8,   9],
        [100,   2,   3,   4,   5,   6,   7,   8,   9],
        [100,   2,   3,   4,   5,   6,   7,   8,   9],
        [100,   2,   3,   4,   5,   6,   7,   8,   9]])

In [31]:
# dim=1 gives column wise for each row together
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[100, 100, 100, 100],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5],
        [  6,   6,   6,   6],
        [  7,   7,   7,   7],
        [  8,   8,   8,   8],
        [  9,   9,   9,   9]])

In [32]:
# squeeze -- removes all single dimensions
y=torch.arange(0,11)
y.shape
y=y.reshape(1,11)
print(f"before squeeze {y.shape}")
y=y.squeeze()
print(f"before squeeze {y.shape}")

before squeeze torch.Size([1, 11])
before squeeze torch.Size([11])


In [33]:
# unsqueeze--> adds an extra dimension
z=y.unsqueeze(dim=1)
z.shape,z

(torch.Size([11, 1]),
 tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]))

In [34]:
# Permute --> rearranges dimensions in a specified order
s=torch.rand((2,5,1))
print(s.shape)
s=s.permute((0,1,2)) #takes the position of each dimension
s

torch.Size([2, 5, 1])


tensor([[[0.9073],
         [0.2783],
         [0.5601],
         [0.7654],
         [0.0221]],

        [[0.3669],
         [0.6187],
         [0.6051],
         [0.3189],
         [0.2776]]])